//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BancoProwayEntities : DbContext
    {
        public BancoProwayEntities()
            : base("name=BancoProwayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assistidos> assistidos { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<episodios> episodios { get; set; }
        public virtual DbSet<filmes> filmes { get; set; }
        public virtual DbSet<perfis> perfis { get; set; }
        public virtual DbSet<series> series { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<temporadas> temporadas { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
