//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class episodios
    {
        public int id_episodio { get; set; }
        public string nome { get; set; }
        public string sinopse { get; set; }
        public Nullable<int> sequencial { get; set; }
    
        public virtual temporadas temporadas { get; set; }
    }
}
